# Site settings

title: EngJamesO
description: "My personal portfolio built with Jekyll"
baseurl: ""
url: "https://eng-james-o.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude: ['README.md', '.gitignore', '.vscode/', '.idea/', 'notes.txt', '.docx', '.wbk', 'scratch/', 'backups/']